# BUILD Phase 1 - Run Composer install
FROM composer:lts AS composer-compile

COPY . /go/src/app/dist/app
WORKDIR /go/src/app/dist/app

RUN composer install --ignore-platform-reqs --optimize-autoloader --no-dev --no-interaction --no-progress --prefer-dist

# BUILD Phase 2 - Compile with FrankenPHP
FROM dunglas/frankenphp:static-builder-musl AS frankenphp-static-builder

COPY --from=composer-compile /go/src/app/dist/app /go/src/app/dist/app

WORKDIR /go/src/app

RUN rm -f dist/cache_key dist/frankenphp-linux-x86_64 && EMBED=dist/app NO_COMPRESS=yes ./build-static.sh

# COPY file dari dalam container ke luar
# docker cp $(docker create --name static-app-tmp <NAMA IMAGE, DAN TAGNYA>):/go/src/app/dist/frankenphp-linux-x86_64 my-app ; docker rm static-app-tmp

# Alternatif build jalankan command ini untuk auto build dan copy file hasil buildnya ke source directory
# docker run --rm -it -v $PWD:/go/src/app/dist/app -w /go/src/app dunglas/frankenphp:static-builder-musl bash -c 'rm -f dist/cache_key dist/frankenphp-linux-x86_64 && EMBED=dist/app NO_COMPRESS=yes ./build-static.sh && cp -av dist/frankenphp-linux-x86_64 /go/src/app/dist/app/my-app'
